version: 0.2

phases:
  install:
    commands:
      - echo Starting build..
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --unsafe-perm
  build:
    commands:
      - echo Build started on `date`
      - echo running test
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
